DevKor-github/saerok-BE

build.gradle
src/main/java/org/devkor/apu/saerok_server/domain/collection/entity/AccessLevelType.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/entity/UserBirdCollection.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/entity/UserBirdCollectionImage.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/entity/Bird.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/entity/BirdDescription.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/entity/BirdImage.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/entity/BirdName.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/entity/BirdTaxonomy.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/habitat/entity/BirdHabitat.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/habitat/entity/HabitatType.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/residency/entity/BirdResidency.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/residency/entity/RarityType.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/residency/entity/RarityTypeEntity.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/residency/entity/ResidencyType.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/residency/entity/ResidencyTypeEntity.java
src/main/java/org/devkor/apu/saerok_server/domain/user/core/entity/GenderType.java
src/main/java/org/devkor/apu/saerok_server/domain/user/core/entity/User.java
src/main/java/org/devkor/apu/saerok_server/global/entity/Auditable.java
src/main/java/org/devkor/apu/saerok_server/global/entity/CreatedAtOnly.java
src/main/java/org/devkor/apu/saerok_server/global/entity/SoftDeletableAuditable.java

feat(entity): JPA 엔티티 설계

---

src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/entity/UserBirdBookmark.java
src/main/java/org/devkor/apu/saerok_server/domain/user/auth/entity/SocialAuth.java
src/main/java/org/devkor/apu/saerok_server/domain/user/auth/entity/UserAuth.java

auth 관련 테이블과 북마크 테이블 엔티티를 추가했습니다.

feat(entity): JPA 엔티티 추가

---

.github/workflows/deploy-to-dev-ec2.yml

개발 서버 배포 자동화를 위한 GitHub Actions 워크플로우를 작성했습니다.

ci: 개발 서버(EC2) 배포 자동화

---

.github/workflows/deploy-to-dev-ec2.yml

#6 에서 설정한 워크플로우가 작동하는 데 실패하여 해당 버그를 해결합니다.

ci: GitHub Actions 워크플로우 오류 수정

---

src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/api/BirdController.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/application/BirdQueryService.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/query/repository/BirdProfileViewRepository.java

입력에 대해 자동완성 제안 목록을 전달하는 api를 구현했습니다.
예를 들어 "까"가 쿼리로 들어오면 까로 시작하는 단어들 + 까가 포함된 단어들이 목록으로 최대 10개까지 전달됩니다.

feat(dex): 자동완성 제안 목록 API

---

src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/api/BookmarkController.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/api/dto/response/BookmarkResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/api/dto/response/BookmarkStatusResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/api/dto/response/BookmarkToggleResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/api/dto/response/BookmarkedBirdDetailResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/application/BookmarkService.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/core/entity/UserBirdBookmark.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/core/mapper/BookmarkMapper.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/core/repository/BookmarkRepository.java
src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/query/mapper/BookmarkMapper.java

도감의 북마크 기능에 대한 API들을 구현했습니다.
CQRS 패턴을 최대한 준수하려고 노력은 했는데 잘 됐는진 모르겠네요 ㅜ

Feat(dex): 도감 북마크 API 구현

---

.github/workflows/deploy-to-dev-ec2.yml

fix(ci): 배포 워크플로우에 환경변수 추가

---

src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionController.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetCollectionDetailResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/core/entity/UserBirdCollection.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/mapper/CollectionWebMapper.java

collectionDetail API 반환 값에 학명 속성을 추가했습니다.

refactor(coll): collection 상세조회 시 학명 반환 추가

---

src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionController.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetCollectionDetailResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionQueryService.java
src/test/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionQueryServiceTest.java

컬렉션 상세 조회 시 비공개 컬렉션은 소유자만 조회 가능하도록 변경했습니다

feat(coll): 컬렉션 상세 조회 시 비공개 컬렉션은 소유자만 조회 가능하도록 변경

---

src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/core/repository/BirdRepository.java

fix(dex): 도감 검색 서식지 필터 오류 해결

---

src/main/java/org/devkor/apu/saerok_server/domain/user/core/service/UserProfilePolicy.java

글자수 제한, 중간에 공백 불가, 한글/영어/숫자 조합으로 제한 추가
아직 닉네임 체크 api 확장은 안했습니다.

feat(user): 유저 닉네임 유효성 검사 목록 추가

---

.github/workflows/deploy-to-dev-ec2.yml

카카오 로그인 관련해 필요한 환경변수 설정하는 것을 배포 workflow에 추가하는 걸 빼먹어서 개발 서버에서 카카오 로그인이 실패한 것을 fix

fix: dev 배포 workflow 환경변수 빼먹은 거 추가

---

src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetNearbyCollectionsResponse.java

주위의 컬렉션 조회 응답 DTO에 위도/경도/주소/위치별칭 추가

feat(map): 주위의 컬렉션 조회 응답 DTO에 위도/경도/주소/위치별칭 추가

---

src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionController.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetNearbyCollectionsResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/MyCollectionsResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionQueryService.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/core/entity/UserBirdCollection.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/mapper/CollectionWebMapper.java

나의 컬렉션 목록 조회 API 응답을 변경했습니다.
- birdName 필드명을 koreanName으로 변경
- 기존 Json Array를 Json Object 안에 감쌈

feat(coll): 나의 컬렉션 목록 조회 API 응답 변경

---

src/main/java/org/devkor/apu/saerok_server/domain/auth/infra/AppleApiClient.java

Apple 정보 로깅
향후 회원 탈퇴 기능 구현하기 위해 확인해 둘 필요 있어 로깅 추가

chore: Apple 정보 로깅

---

src/main/java/org/devkor/apu/saerok_server/global/security/CorsProperties.java
src/main/java/org/devkor/apu/saerok_server/global/security/SecurityConfig.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml

feat: cors 설정 추가

---

.github/workflows/deploy-to-dev-ec2.yml
.github/workflows/deploy-to-prod-ec2.yml
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml

한국 시간 기준으로 각 서버에 들어오는 요청/응답 로깅을 위해 서버 타임존 설정 및 Tomcat 액세스 로그 활성화

chore: 개발/운영 서버 타임존 설정, Tomcat 액세스 로그 활성화

---

.github/workflows/deploy-to-dev-ec2.yml
.github/workflows/deploy-to-prod-ec2.yml
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml

* chore: 개발/운영 서버 타임존을 서울(+09:00)로
로그 보기 편하려고
* chore: Tomcat 액세스 로그 활성화
요청/응답 현황 로깅 목적

chore: 개발/운영 서버 타임존 설정, Tomcat 액세스 로그 활성화 (#62)

---

.github/workflows/deploy-to-dev-ec2.yml

fix: 환경변수 이름 변경 빼먹은 부분

---

src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionLikeController.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionLikeCommandService.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionLikeQueryService.java
src/test/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionLikeCommandServiceTest.java

컨벤션대로 CQRS 패턴 따르도록 변경했고, 그에 따라 테스트명도 수정
closes #94 
closes #90 
버그 픽스의 경우, 다시 보니까 테스트에서 자기 자신의 비공개 컬렉션 조회 시 예상 결과를 true로 했더라구요. 
테스트는 상황 설계하기 나름인 것 같아서 그냥 그대로 뒀습니다.

chore(coll): 컬렉션 좋아요 서비스 구조 변경

---

src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionCommentController.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionCommentLikeController.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetCollectionCommentsResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommentLikeCommandService.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommentLikeQueryService.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommentQueryService.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/core/entity/UserBirdCollectionCommentLike.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionCommentLikeRepository.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/mapper/CollectionCommentWebMapper.java
src/main/resources/db/migration/V29__add_comment_like_table.sql
src/test/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommentQueryServiceTest.java

commentLike 도메인을 구현했습니다
closes #100 
@soonduck-dreams 
기존 comment 목록 조회에 좋아요 관련 필드 추가하면서 쿼리 호출을 최적화해봤는데 어떤지 잘 모르겠네요...
코드가 좀 어지러운가 싶기도 하고, 보다보면 또 괜찮나 싶기도 하고... ㅠ

feat: 댓글 좋아요 기능 구현

---

src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetCollectionCommentsResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommentQueryService.java
src/main/java/org/devkor/apu/saerok_server/domain/collection/mapper/CollectionCommentWebMapper.java
src/test/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommentQueryServiceTest.java
src/test/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionCommentRepositoryTest.java

댓글 목록 조회 응답에 '유저 닉네임'과 '내 댓글 여부' 필드를 추가했습니다.
closes #108
@soonduck-dreams 

feat(coll): 댓글 조회에 새로운 필드 추가

---

src/main/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionRepository.java
src/main/java/org/devkor/apu/saerok_server/domain/profile/api/ProfileController.java
src/main/java/org/devkor/apu/saerok_server/domain/profile/api/dto/response/UserProfileResponse.java
src/main/java/org/devkor/apu/saerok_server/domain/profile/application/ProfileQueryService.java
src/main/java/org/devkor/apu/saerok_server/domain/profile/mapper/UserProfileMapper.java

feat: 특정 사용자의 프로필 조회 API 구현

---

src/main/resources/config/user-profile-images-default.yml
src/main/resources/db/migration/V53__migrate_default_profile_image_variants.sql

기본 프로필 사진 2, 3번(진한 노랑, 중간 파랑)만 남기기
closes #149 

refactor(db): 유저 프로필 사진 2, 3번만 남기기

---

.github/workflows/deploy-to-prod-ec2.yml

fix: 운영 workflow 배포 실패 원인 해결 (#152)

---

src/main/resources/db/migration/V54__update_bird_images.sql
src/main/resources/db/migration/V55__update_scientific_name.sql

일부 새들의 도감 이미지를 변경했습니다.
일부 새의 분류정보를 변경했습니다. (북방쇠찌르레기: _Sturnus sturninus_ -> _Agropsar sturninus_)
Closes #155 
Closes #154 

feat: 도감 업데이트

---

src/main/resources/db/migration/V56__add_new_bird_jibbidulgi.sql

테스트 실패 덕분에 bird seq 값을 조정하지 않은 실수를 발견하였고 수정함

fix: bird seq를 올바른 값으로 보정

---

.github/workflows/deploy-to-dev-ec2.yml
Dockerfile
docker-compose.local.yml

서버가 Docker 컨테이너 위에서 돌아가도록 전환하는 작업입니다
앞으로 Redis, Kafka 같은 다른 기술 스택이 붙을 때도 컨테이너로 맞춰서 관리하면 훨씬 깔끔하고 안정적으로 확장할 수 있어요
개발 서버 배포 로직을 크게 바꾼 거라 처음엔 삐걱거릴 수 있어요
그래서 문제 fix를 위한 PR이 몇 번 더 올라올 수 있다는 점 참고해주세요!

ci(infra): EC2 배포를 Docker Compose 기반으로 전환

---

.github/workflows/deploy-to-dev-ec2-docker.yml
Dockerfile
deploy/docker-compose.dev.yml
deploy/docker-compose.override.yml
deploy/docker-compose.yml

GitHub Actions 워크플로 추가로 개발 환경 배포 자동화.
Dockerfile 간소화 및 unnecessary 설정 제거.

feat: 배포 자동화 및 Dockerfile 최적화

---

.github/workflows/deploy-to-dev-ec2-docker.yml
deploy/docker-compose.dev.yml
deploy/docker-compose.yml

dev 환경에서 RAM 기반 env 파일 주입 기능 추가.
docker-compose 파일 구조 단순화 및 배포 스크립트 보완.

feat: dev 환경 설정 및 배포 스크립트 개선

---

.github/workflows/deploy-to-dev-ec2-docker.yml
.github/workflows/deploy-to-dev-ec2.yml
README.md
down.sh
up.sh

갖은 시도 끝에 겨우 Docker 배포 워크플로로 전환 성공했습니다~
Redis 같은 추가 도구 붙이기 편하게 하기 위한 작업이었어요
@pizzazoa 
* 앱 실행 환경을 **박스(컨테이너)** 안에 담아 어디서든 똑같이 실행되게 해주는 도구
---
* **Dockerfile** → 컨테이너 만드는 레시피 🍲
* **docker-compose.yml** → 기본 세팅 📦
* **docker-compose.override.yml** → 로컬 개발 세팅 오버레이 💻
* **docker-compose.dev.yml** → 개발 서버(EC2) 세팅 오버레이 ☁️
* **deploy-to-dev-ec2-docker.yml** → 깃허브 액션 자동 배포 🤖
* **up.sh / down.sh** → 로컬 서버 올리고 내리는 버튼 🔼🔽
---
1. **Docker Desktop 켜기**
2. **터미널 열기 (Git Bash 권장)**
3. 서버 올리기:
```bash
./up.sh
```
4. 서버 내리기:
```bash
./down.sh
```
---
* 환경 차이 없는 실행 (로컬 ↔ 서버 동일)
* Redis 같은 추가 도구 붙이기 쉬워짐
---
* 처음에 EC2에서 컨테이너가 CPU 100% 먹고 서버가 뻗어버림 💥
* 해결 → 컨테이너에 **자원 제한** 걸어서 안정화 ✅
---
👉 앞으로는 초록색 버튼 말고 `./up.sh` / `./down.sh`\*\*로 서버 다루면 돼요!

ci: Docker 배포 워크플로를 기본으로 설정

---

deploy/docker-compose.override.yml
down.sh
up.sh

chore: docker-compose override 및 스크립트 수정

---

src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionLikeCommandService.java
src/main/java/org/devkor/apu/saerok_server/domain/community/api/dto/common/CommunityCollectionInfo.java
src/main/java/org/devkor/apu/saerok_server/domain/community/application/CommunityDataAssembler.java
src/main/java/org/devkor/apu/saerok_server/domain/community/application/CommunityQueryService.java
src/main/java/org/devkor/apu/saerok_server/domain/community/core/entity/PopularCollection.java
src/main/java/org/devkor/apu/saerok_server/domain/community/core/repository/CommunityRepository.java
src/main/java/org/devkor/apu/saerok_server/domain/community/core/repository/PopularCollectionRepository.java
src/main/java/org/devkor/apu/saerok_server/domain/community/mapper/CommunityWebMapper.java
src/main/resources/db/migration/V57__create_popular_collection_table.sql
src/test/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionLikeCommandServiceTest.java
src/test/java/org/devkor/apu/saerok_server/domain/community/application/CommunityQueryServiceTest.java
src/test/java/org/devkor/apu/saerok_server/domain/community/core/repository/CommunityRepositoryTest.java

인기 기준치를 달성한 새록들을 저장하는 인기 컬렉션 테이블을 추가하고 그에 맞게 기존 로직들을 일부 수정했습니다

feat(): 인기 컬렉션 테이블 구현
