DevKor-github/saerok-BE

- .github/workflows/deploy-to-dev-ec2.yml
- build.gradle
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/controller/BirdController.java
- src/main/java/org/devkor/apu/saerok_server/system/controller/SystemController.java
- src/main/resources/application.yml
API 명세 관리를 위해 Swagger를 설정하고, 도감 API 명세 초안을 추가했습니다.
이런 식으로 API 명세를 확인할 수 있으며, 아직 실제 구현하지 않고 명세만 있는 경우는 "미구현" 표시로 구분합니다.
@pizzazoa 
지금 BirdController 파일을 보시면 실제 구현은 없고 Swagger 명세만 만들어뒀습니다. 앞으로 개발할 때도 이런 식으로 "명세 만들어서 공유해서 의견 받고 -> 명세 확정해서 개발하기" 방법으로 할까 싶은데 어떠신가요??
> feat(dex): Swagger 설정 및 도감 API 명세 초안 추가

- .github/workflows/deploy-to-dev-ec2.yml
배포 직전 테스트할 때 ./gradlew build 대신 ./gradlew test bootJar 쓰도록 변경.
build를 쓰면 이상한 JAR 파일이 EC2로 전송되어서 기존 워크플로우대로 안 돌아감
> fix(ci): 배포 워크플로우 오류 수정

- src/main/resources/db/migration/V5__alter_rarity_priority.sql
- src/test/resources/db/migration/test/V4__bird_update_trigger.sql
- src/test/resources/db/migration/test/V5__alter_rarity_priority.sql
계절별 희귀도 우선순위를 변경함.
기존에는 COMMON > UNSPECIFIED > RARE 순이었는데, COMMON > RARE > UNSPECIFIED 순으로 변경.
예를 들어 어떤 새가 3월에는 드물고 4월에는 희귀도 미지정일 때, 기존에는 해당 새의 봄 희귀도는 "미지정"으로 결정됨.
이제부터는 해당 새의 봄 희귀도가 "드묾"으로 결정됨.
미지정은 "흔함과 드묾 사이의 희귀도"라기보다는 "흔한지 드문지 확실치 않다"고 보는 게 맞을 것 같아서 이렇게 변경했음
> feat(db): 계절별 희귀도 우선순위 변경

- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/api/BirdController.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/application/BirdQueryService.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/query/mapper/BirdProfileViewMapper.java
- src/main/java/org/devkor/apu/saerok_server/global/exception/GlobalExceptionHandler.java
- src/main/java/org/devkor/apu/saerok_server/global/exception/NotFoundException.java
id로 특정 조류의 상세정보를 조회하는 GET api입니다
BirdController, BirdQueryService, BirdProfileViewMapper 각각에 필요한 메서드들을 구현했습니다.
@soonduck-dreams 
Mapper를 보시면, 
sizeCategory 정보를 매핑할 때 SizeCategoryService를 이용하기 위해 오버로드 대신 context로 해결했습니다.
이렇게 하는 게 더 깔끔한 것 같아서 해봤는데, 다른 해결법이 있다거나 다른 방식으로 했으면 좋겠다거나 하시다면 말씀해주세요.
추후 에러 핸들러도 추가할 예정입니다(아마 400번대 에러로 처리할 듯 합니다).
결과는 어제 보여드린 것처럼 잘 나오더라구요 :)
> feat(dex): 특정 조류 상세 정보 조회 API

- build.gradle
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/api/BirdController.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/application/BirdQueryService.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/application/dto/BirdSearchCommand.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/domain/repository/BirdRepository.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/query/dto/BirdSearchDto.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/query/enums/BirdSearchSortDirType.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/query/enums/BirdSearchSortType.java
- src/main/java/org/devkor/apu/saerok_server/global/exception/BadRequestException.java
- src/main/java/org/devkor/apu/saerok_server/global/exception/GlobalExceptionHandler.java
- src/main/java/org/devkor/apu/saerok_server/global/util/EnumParser.java
도감 검색/조회 API에 정렬 기능을 추가했습니다.
이용 가능한 정렬 기준: id, 한국 이름, 몸 크기
각각 오름차순/내림차순 가능
> feat(dex): 도감 검색/조회 API에 정렬 기능 추가

- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionController.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommandService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/dto/DeleteCollectionCommand.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionImageRepository.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionRepository.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/mapper/CollectionWebMapper.java
컬렉션 삭제 API를 구현했습니다.
S3의 이미지를 먼저 삭제한 뒤, DB 데이터를 삭제합니다.
> feat(coll): 컬렉션 삭제 API 구현

- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionController.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/request/CreateCollectionRequest.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommandService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/dto/CreateCollectionCommand.java
컬렉션 등록 API 요청 시 tempBirdName을 받지 않도록 수정했습니다. (회의로 결정된 사항 반영)
* 내부적으로 tempBirdName을 항상 null로 설정하게 했습니다
> chore(coll): 컬렉션 등록 API에서 tempBirdName 받지 않게 수정

- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionController.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/request/UpdateCollectionRequest.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetCollectionEditDataResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/UpdateCollectionResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommandService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionImageCommandService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionQueryService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/dto/GetCollectionEditDataCommand.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/dto/UpdateCollectionCommand.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/entity/UserBirdCollection.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionImageRepository.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/mapper/CollectionWebMapper.java
- src/main/java/org/devkor/apu/saerok_server/global/exception/GlobalExceptionHandler.java
- src/main/java/org/devkor/apu/saerok_server/global/exception/S3DeleteException.java
컬렉션 수정 API를 구현했습니다.
세부적으로는 3가지 API를 추가했습니다.
- 컬렉션 수정용 상세 조회
- 컬렉션 메타데이터 수정 (이미지 제외한 정보들 수정)
- 컬렉션 이미지 삭제 (컬렉션 이미지를 수정하고 싶을 경우, 기존의 컬렉션 이미지 등록하는 API와 함께 사용)
> feat(coll): 컬렉션 수정 API 구현

- src/main/resources/db/migration/V10__delete_bird_duplicate_data.sql
도감 중복 아종 데이터를 제거했습니다. (이전에 회의해서 결정한 바에 따름)
기존 17쌍이 중복되던 것에서 하나씩 아종 데이터를 제거했고, 이제 도감 조류 개수는 585개 (602 - 17) 입니다
> chore(dex): 도감 중복 아종 데이터 제거

- src/main/java/org/devkor/apu/saerok_server/system/controller/SystemController.java
ELB 대응을 위한 헬스 체크 API를 구현했습니다.
단순히 현재 서버가 살아 있는지를 확인하기 위한 용도입니다
도메인 주소 및 HTTPS 적용에 앞서 ELB(Elastic Load Balancer)를 세팅 중입니다!
앞으로 사용자 요청은 제일 먼저 이 ELB가 받아들인 뒤, 뒤쪽의 웹 서버(EC2)에게 넘겨주게 되는데요. ELB는 정기적으로 EC2 인스턴스가 살아있는지 확인을 하기 위한 요청을 보냅니다. 그래서 200번대 응답이 오면 잘 살아있는 것으로 인지를 합니다. 이것을 헬스 체크라고 하구요. `GET /health`로 헬스 체크 확인을 하도록 세팅을 해뒀고, 이에 대응하기 위한 작업입니다
> chore(infra): ELB 헬스 체크 API 구현

- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionController.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetNearbyCollectionsResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/MyCollectionsResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommandService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionQueryService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/dto/GetNearbyCollectionsCommand.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionRepository.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/infra/PointFactory.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/mapper/CollectionWebMapper.java
- src/test/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionQueryServiceTest.java
- src/test/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionRepositoryTest.java
주위의 컬렉션 조회 API를 구현했습니다.
다음 3가지 케이스에 대응합니다.
- 내 지도 (반경 내 나의 컬렉션)
- 우리 지도 (반경 내 나의 컬렉션 + 반경 내 타인의 공개된 컬렉션)
- (비회원용) 우리 지도 (반경 내 타인의 공개된 컬렉션)
> feat(map): 주위의 컬렉션 조회 API 구현 (지도)

- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionController.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/request/UpdateCollectionRequest.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetCollectionEditDataResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/UpdateCollectionResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommandService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionQueryService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/dto/UpdateCollectionCommand.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/mapper/CollectionWebMapper.java
- 컬렉션 수정 API 응답 수정 (imageUrls -> imageUrl)
- 컬렉션 수정용 상세 조회 API 응답 수정 (images[0].id, images[0].url -> imageId, imageUrl)
- 컬렉션 수정 API에 accessLevel 추가 (공개, 비공개 수정 가능)
> feat: 컬렉션 수정 계열 API 응답 수정 및 컬렉션 수정 API에 accessLevel 추가

- src/main/java/org/devkor/apu/saerok_server/domain/auth/api/AuthController.java
- src/main/java/org/devkor/apu/saerok_server/domain/auth/api/dto/request/KakaoLoginRequest.java
카카오 소셜 로그인 API HTTP 메서드를 GET에서 POST로 변경했습니다
이에 따라 기존 쿼리 파라미터 방식(`/kakao/login?accessToken=abc`)이 아닌 JSON body로 인가 코드 또는 액세스 토큰을 보내야 합니다
> feat: 카카오 소셜 로그인 API HTTP 메서드 변경 (GET -> POST)

- src/main/java/org/devkor/apu/saerok_server/domain/user/api/response/GetMyUserProfileResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/user/application/UserQueryService.java
- src/main/java/org/devkor/apu/saerok_server/domain/user/core/entity/User.java
- src/main/java/org/devkor/apu/saerok_server/global/entity/Auditable.java
- src/main/java/org/devkor/apu/saerok_server/global/util/OffsetDateTimeLocalizer.java
- src/main/resources/db/migration/V21__add_joined_at_to_user.sql
회원 정보 조회에 가입 일자를 포함시켰습니다.
users 테이블에 joined_at이라는 별도 필드를 추가했습니다
처음에는 created_at이 가입 일자 역할도 해줄 거라고 생각했는데, 사용자 탈퇴 시 soft delete했다가 재가입하는 상황을 생각했을 때, 가장 최근 가입 시각을 나타내는 별도 필드를 두는 것이 의미상 적절하겠다 싶더라구요 (created_at을 재가입할 때 변경하는 것은 부적절하다는 판단)
또 OffsetDateTimeLocalizer라는 유틸성 클래스를 하나 추가했어요. OffsetDateTime을 적절한 타임존의 (사실상 서울 기준) LocalDate 또는 LocalDateTime으로 변환해줄 책임을 갖는 녀석입니다. 사용자 가입 시각, 컬렉션(새록) 생성 시각 등등 잠재적으로 사용자에게 시각 또는 날짜 정보를 제공해줄 일이 생길 수 있는데, OffsetDateTime 타입을 그대로 제공한다면 그게 서울 기준이라는 보장이 없어서 이를 안전하게 서울 시각으로 변환해서 사용자에게 제공해줄 필요가 있거든요. 근데 이걸 매번 각 코드에서 일일이 서울 기준 LocalDate로 바꾸는 작업을 해서 코드 중복을 만들 가능성을 차단하기 위해 OffsetDateTimeLocalizer가 이 일을 맡게 한 것입니당
> feat(user): 회원 정보 조회에 가입 일자 포함

- .github/workflows/deploy-to-dev-ec2.yml
- .github/workflows/deploy-to-prod-ec2.yml
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/core/entity/BirdImage.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/core/mapper/BirdMapper.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/query/mapper/BirdProfileViewMapper.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/query/view/BirdProfileView.java
- src/main/java/org/devkor/apu/saerok_server/domain/dex/bookmark/query/mapper/BookmarkMapper.java
- src/main/java/org/devkor/apu/saerok_server/global/util/ImageDomainService.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/db/migration/V23__add_object_key_to_bird_img.sql
- src/main/resources/db/migration/V24__replace_s3_url_with_object_key_in_bird_profile_mv.sql
- src/main/resources/db/migration/V25__drop_s3_url_from_bird_img.sql
차후 관리자가 운영 중인 서비스의 도감 이미지를 수정할 수 있게 될 가능성을 고려했을 때, 기존 개발 서버와 운영 서버가 동일한 S3 버킷을 참조하는 구조는 리스크가 있어 도감 이미지 버킷을 개발 서버용/운영 서버용으로 분리했습니다. 또한 기존에는 도감 이미지의 Full URL을 DB에 직접 저장하고 있었던 방식을 개선하여, object key만 저장하고 코드에서 도메인과 조합해 URL을 생성하는 방식으로 변경했습니다
bird_image 테이블에서 s3_url 칼럼을 삭제하고 object_key 칼럼을 추가했어요
- 기존에는 s3_url(`https://abcdef.cloudfront.net/raw/12345-67890.jpg`)을 DB에 직접 저장하고 제공
- 이제는 object_key(`raw/12345-67890.jpg`)를 들고 있다가
- 사용자에게 URL 제공 시: `ImageDomainService.toDexImageUrl(object_key)`로 실제 URL로 변환
- (이전에 CloudFrontUrlService였던 거 이름을 ImageDomainService로 바꿨습니다)
이런 느낌
> chore: 도감 이미지 버킷 dev/prod 분리

- README.md
- build.gradle
Jacoco 도입해서, gradlew test 시 코드 커버리지 간단히 확인할 수 있게 설정
@pizzazoa 
README 파일에서 "테스트 구성" 파트에 내용 추가했으니 읽어보세용
> chore: Jacoco 도입해서, gradlew test 시 코드 커버리지 간단히 확인할 수 있게 설정

- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionController.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetCollectionDetailResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetNearbyCollectionsResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/MyCollectionsResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionQueryService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/mapper/CollectionWebMapper.java
- src/test/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionQueryServiceTest.java
컬렉션 조회 응답에 댓글 수 필드를 포함시켰습니다.
추가적으로, likeCount가 21억...을 넘을 것 같진 않아서 int로 했었던 것을 컨벤션에 따라 Long으로 일단 바꿨습니다.
> refactor(coll): 컬렉션 조회 응답에 댓글 수 집계 추가

- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionCommentLikeRepository.java
- src/test/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionCommentLikeRepositoryTest.java
새록 댓글 목록 조회 API 호출 시, 좋아요가 0인 댓글이 포함되어 있을 경우 정상적으로 처리하지 못하는 버그를 수정했습니다.
새록 댓글의 좋아요 repository 테스트를 추가했습니다.
@pizzazoa 
트러블슈팅 로그 공유해요!
- 새록 댓글 목록 조회 중 서버 내부 오류 발생
- `likeCounts에 댓글 ID 1이 없습니다` 오류 발생
- <img width="1181" height="477" alt="image" src="https://github.com/user-attachments/assets/ba1e3ad6-e868-4e3c-84cb-88c6145f7d83" />
- 외부에서 준 likeCounts가 비정상이라는 뜻
- likeCounts를 준 것은 `countLikesByCommentIds`
- <img width="708" height="56" alt="image" src="https://github.com/user-attachments/assets/c90c5ddc-f7fe-4d30-8538-f07453f4150d" />
- <img width="721" height="161" alt="image" src="https://github.com/user-attachments/assets/0afcc053-553f-442b-92b0-a31c8bc4ad2c" />
- 살펴 보니 기존 `countLikesByCommentIds` 구현이 잘못되었음 (좋아요가 없는 댓글일 경우 `results`에 아예 해당 댓글 id가 포함되지 않음)
- [v] …
> fix: countLikesByCommentIds 로직 에러 픽스

- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/CollectionCommentReportController.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/ReportCollectionCommentResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommentReportCommandService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/entity/UserBirdCollectionCommentReport.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/repository/CollectionCommentReportRepository.java
- src/main/resources/db/migration/V30__add_comment_report_table.sql
댓글 신고 기능을 구현했습니다.
당장은 신고 사유를 받는다던가 하는 게 없어서 간단하게 구현했습니다.
댓글 id뿐만 아니라 댓글 내용까지 받는 이유는, 신고된 상태에서 수정하거나 하면 왜 신고가 들어왔는지 추적이 안될 수 있어서 로그 느낌..으로 필드를 추가했습니다.
> feat(coll): 댓글 신고 기능 구현

- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/BirdIdSuggestionController.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/request/SuggestBirdIdRequest.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/request/SuggestOrAgreeRequest.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/AgreeStatusResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/DisagreeStatusResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/GetBirdIdSuggestionsResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/api/dto/response/SuggestBirdIdResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/BirdIdSuggestionCommandService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/application/BirdIdSuggestionQueryService.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/entity/BirdIdSuggestion.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/repository/BirdIdSuggestionRepository.java
- src/main/java/org/devkor/apu/saerok_server/domain/collection/core/repository/dto/BirdIdSuggestionSummary.java
- src/main/resources/db/migration/V38__add_type_to_bird_id_suggestion.sql
- src/test/java/org/devkor/apu/saerok_server/domain/collection/application/BirdIdSuggestionCommandServiceTest.java
- src/test/java/org/devkor/apu/saerok_server/domain/collection/application/BirdIdSuggestionQueryServiceTest.java
- src/test/java/org/devkor/apu/saerok_server/domain/collection/core/repository/BirdIdSuggestionRepositoryTest.java
- src/test/java/org/devkor/apu/saerok_server/testsupport/builder/SuggestionBuilder.java
프론트의 요청에 따라 동정 의견 API를 수정했습니다.
요청 사항
- disagree에 대한 count와 isDisagreedByMe 필드를 응답 dto에 포함할 것
- 동정 제안과 동의를 분리하고, 동의, 비동의 2개의 API를 각각 토글로 만들 것
위 요청 사항을 반영하여 수정했습니다.
V37까지 다른 작업들에 쓰고 있는 중이라 V38로 작업했습니다.
> feat(coll): 동정 의견 API 수정

- src/main/java/org/devkor/apu/saerok_server/domain/user/application/UserCommandService.java
- src/test/java/org/devkor/apu/saerok_server/domain/user/application/UserCommandServiceTest.java
사용자가 요청에 넣은 값(objectKey)을 그대로 써서 프사 URL 값으로 돌려주는 것에서, 실제 프사 URL 값을 찾아서 보여주도록 수정
> fix: 회원 정보 수정 API 응답에서 프사 URL 제대로 표시 안 하는 문제 수정

- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/assembly/render/ActionNotificationRenderer.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/infra/fcm/FcmPushGateway.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/infra/local/LocalPushGateway.java
- src/main/java/org/devkor/apu/saerok_server/global/core/config/feature/NotificationMessagesConfig.java
- src/main/resources/application.yml
- src/main/resources/config/notification-messages.yml
이번 PR에서는 알림 메시지를 코드에서 떼어내서 설정 파일(YAML)로 관리하게 바꿨고,
환경마다 PushGateway가 다르게 동작하도록 분리했어요.
---
* `config/notification-messages.yml` 파일 추가
* `NotificationMessagesConfig` 클래스로 메시지를 불러오고, `ActionNotificationRenderer`에서 템플릿 기반으로 메시지 만드는 구조로 변경했어요.
* 이제 `{actorName}`, `{comment}` 같은 변수를 치환해서 메시지를 만들 수 있어요.
```yaml
notification-messages:
types:
LIKED_ON_COLLECTION:
push-title: "{actorName}"
push-body: "나의 새록을 좋아해요."
in-app-body: "{actorName}님이 나의 새록을 좋아해요."
COMMENTED_ON_COLLECTION:
push-title: "{actorName}"
push-body: "나의 새록에 댓글을 남겼어요. \"{comment}\""
in-app-body: "{actorName}님이 나의 새록에 댓글을 남겼어요. \"{comment}\""
SUGGESTED_BIRD_ID_ON_COLLECTION:
push-title: "동정 의견 공유"
push-body: "두근두근! 새로운 의견이 공유되었어요. 확인해볼까요?"
in-app-body: "두근두근! 새로운 의견이 공유되었어요. 확인해볼까요?"
```
---
* **dev/prod** → `FcmPushGateway` (실제로 푸시 …
> feat: 알림 메시지 외부화 및 환경별 PushGateway 분리

- src/main/java/org/devkor/apu/saerok_server/domain/notification/api/dto/response/GetNotificationsResponse.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/NotificationQueryService.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/adapter/CollectionTargetMetadataAdapter.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/assembly/store/InAppNotificationWriter.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/facade/NotificationPublisher.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/facade/NotifyActionDsl.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/model/payload/ActionNotificationPayload.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/model/payload/NotificationPayload.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/port/TargetMetadataPort.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/core/entity/Notification.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/mapper/NotificationWebMapper.java
- src/main/resources/db/migration/V50__add_payload_to_noti_and_migrate_related_id.sql
- src/main/resources/db/migration/V51__delete_related_id_from_noti.sql
- src/test/java/org/devkor/apu/saerok_server/domain/collection/application/BirdIdSuggestionCommandServiceTest.java
- src/test/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionCommentCommandServiceTest.java
- src/test/java/org/devkor/apu/saerok_server/domain/collection/application/CollectionLikeCommandServiceTest.java
Closes #134 
알림 목록 응답에서 **컬렉션 이미지 URL**과 **액터 프로필 이미지 URL**도 같이 달아달라는 FE 요구사항에 대응했습니다.
이를 반영하면서 구조를 손봤습니다:
* notification 테이블에서 `related_id` 칼럼을 제거하고, 알림별 메타데이터는 **payload(jsonb)** 로 일원화했어요.
* `payload`에는 TargetType에 맞는 키(`collectionId`, `collectionImageUrl`)를 넣고, 응답에는 `actorProfileImageUrl`도 추가했어요.
* NotifyActionDSL은 **여전히 외부 Repository/Service를 몰라요**. 필요한 메타데이터는 밖에서 모아서(enrich) DSL에 건네주고, NotifyActionDSL은 누군가의 어떤 행동이 일어났다는 것을 선언하고 NotificationPublisher에게 알려주는 일에 집중해요.
👉 결과적으로, **프론트가 요청한 이미지 정보 제공**을 충족하면서, **앞으로 알림별 다양한 메타데이터 확장**에도 대비한 구조로 바뀌었습니다.
> feat: 알림 응답 확장: 컬렉션 이미지·액터 프로필 이미지 추가 및 payload 구조 전환

- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/assembly/store/InAppNotificationWriter.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/dto/PushMessageCommand.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/facade/NotificationPublisher.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/core/repository/NotificationRepository.java
- src/main/java/org/devkor/apu/saerok_server/domain/notification/infra/fcm/FcmMessageClient.java
푸쉬 알림을 눌렀을 때 곧바로 읽음 처리를 할 수 있도록 알림 id 필드를 추가했습니다. (프론트 요청사항)
> feat(): 푸쉬 메시지에 알림 id 필드 추가

- src/main/java/org/devkor/apu/saerok_server/domain/notification/application/NotificationCommandService.java
알림 삭제 시에도 사일런트 푸쉬가 발송되도록 했습니다.
> feat(): 알림 삭제에도 사일런트 푸쉬 추가

- .github/workflows/deploy-to-prod-ec2.yml
> fix: 운영 workflow 배포 실패 원인 해결

- src/main/java/org/devkor/apu/saerok_server/domain/dex/bird/query/mapper/BirdProfileViewMapper.java
현재 프론트의 도감 데이터 처리 로직과 호환성을 맞추기 위한 임시 조치. 추후 프론트에서 nibrUrl null 처리 대응이 되면 지우도록 TODO 주석 달았음
> chore: nibrUrl이 null이면 대신 빈 문자열로 응답

- src/main/java/org/devkor/apu/saerok_server/domain/auth/api/AuthController.java
- src/main/java/org/devkor/apu/saerok_server/domain/auth/api/dto/request/KakaoLoginRequest.java
- src/main/java/org/devkor/apu/saerok_server/domain/auth/application/AbstractSocialAuthService.java
- src/main/java/org/devkor/apu/saerok_server/domain/auth/application/KakaoAuthService.java
- src/main/java/org/devkor/apu/saerok_server/domain/auth/infra/KakaoApiClient.java
- src/main/java/org/devkor/apu/saerok_server/domain/auth/infra/KakaoAuthClient.java
- src/main/java/org/devkor/apu/saerok_server/domain/auth/infra/KakaoRedirectUriResolver.java
- src/main/java/org/devkor/apu/saerok_server/domain/user/core/entity/UserRoleType.java
- src/main/java/org/devkor/apu/saerok_server/global/core/properties/KakaoRedirectRoutingProperties.java
- src/main/resources/application-local.yml
- up.sh
- 관리자 카카오 로그인을 위한 서비스 서버 지원을 추가했습니다
- 기존 ADMIN 권한을 ADMIN_VIEWER, ADMIN_EDITOR 권한으로 세분화했습니다
> feat: 관리자 카카오 로그인 지원
